name: checklist_api
description: RESTful API server for CheckList todo app

version: 1.0.0

environment:
  sdk: ^3.2.0

dependencies:
  # Web server framework
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_web_socket: ^1.0.4
  shelf_static: ^1.1.2
  shelf_cors_headers: ^0.1.5

  # HTTP and routing
  http: ^1.1.0

  # JSON serialization
  json_annotation: ^4.8.1

  # Database
  sqlite3: ^2.4.0
  drift: ^2.14.1

  # Authentication and security
  dart_jsonwebtoken: ^2.12.2
  crypto: ^3.0.3
  bcrypt: ^1.1.3

  # Validation
  validators: ^3.0.0

  # Logging
  logging: ^1.2.0

  # Configuration
  args: ^2.4.2
  dotenv: ^4.0.1

  # Utilities
  uuid: ^4.2.1
  intl: ^0.19.0

dev_dependencies:
  # Build runner
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  drift_dev: ^2.14.1

  # Testing
  test: ^1.24.0
  shelf_test_handler: ^1.0.0

  # Linting
  very_good_analysis: ^5.1.0

executables:
  server: main
